- interfaceType: Extengerator.Sample.EventHandlers.IAutoRegisterHandler
  #language=c#
  template: |-
    using Extengerator.Sample.SomeEventBus;
    using Extengerator.Sample.SomeDependencyInjectionFramework;

    namespace Extengerator.Sample.EventHandlers
    {{
      public static partial class EventHandlersExtensions
      {{
        public static void RegisterAllHandlers(this IEventBus eventBus, IContainer container)
        {{
          {0}
        }}
      
        public static void DeregisterAllHandlers(this IEventBus eventBus)
        {{
          {1}
        }}
      }}
    }}
  #language=c#
  replacer:
    - eventBus.Register(container.Resolve<{0}>());
    - eventBus.DeregisterAll<{0}>();
  fileName: EventHandlersExtensions
