- interfaceType: Extengerator.SimpleSample.EventHandlers.IAutoRegisterHandler
  #language=c#
  template: |-
    using Extengerator.SimpleSample.SomeEventBus;
    using Extengerator.SimpleSample.SomeDependencyInjectionFramework;

    namespace Extengerator.SimpleSample.EventHandlers
    {{
      public static partial class EventHandlersExtensions
      {{
        public static void RegisterAllHandlers(this IEventBus eventBus, IContainer container)
        {{
          {0}
        }}
      
        public static void DeregisterAllHandlers(this IEventBus eventBus)
        {{
          {1}
        }}
      }}
    }}
  #language=c#
  replacer:
    - eventBus.Register(container.Resolve<{0}>());
    - eventBus.DeregisterAll<{0}>();
  fileName: EventHandlersExtensions
